spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/sajat_adatbazis
spring.datasource.username=postgres
spring.datasource.password=jelszo
spring.jpa.hibernate.ddl-auto=update
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
